services:
  node-master:
    image: spark-base:latest
    container_name: node-master
    hostname: node-master
    ports:
      - "8081:8080"
      - "7077:7077"
    networks:
      cluster-network:
        aliases: 
          - node-master
  node-slave1:
    image: spark-base:latest
    container_name: node-slave1
    hostname: node-slave1
    depends_on:
      - node-master
    networks:
      cluster-network:
        aliases: 
          - node-slave1
networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default
